### ISSUE TITLE
Feature Request - Add high resolution images and icons for App and Portal

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#15]
# Details
**Category:** Feature Request

**Short Description:** Add high resolution images and icons for App and Portal

**Full Description:**
If the user saves the app to their desktop we should include a high-res logo and graphic.

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/IMG_2707-1.jpg)

**Priority:** Medium
**User Type:** All User (Portal + App)
**Device:** Mobile - iOS / Apple
**Browser:** Apple Safari
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Stephen M. Yoss (steve@clockworksafety.com)
Devmatics, LLC

# Related Issues

- [x] https://github.com/devmatics/clockwork-app/issues/17
- [x] https://github.com/devmatics/clockwork-app/issues/18

**Comment by smyoss** [comment]
@devmatics-issues -- Additionally, the issue is if the user bookmarks the page and logs out. When they log back in they get a 404 error. In a nutshell, if the user tries to access a page that requires authentication it should take them to the login screen, they authentication, and then redirect back to the page they originally requested.

**Comment by WardenDrew** [comment]
Disregarding for Portal as Portal is not mobile first

**Comment by ARegalbuto** [comment]
Download to desktop fixed.  Populates icon. 
![image](https://user-images.githubusercontent.com/92471253/148861994-8c90b388-f926-43cd-b712-9bb809681d23.png)
